default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST") %>

development:
  <<: *default
  database: ivecolor_development

test:
  <<: *default
  database: ivecolor_test

production:
  <<: *default
  database: ivecolor_production
